accent = "#ffffff"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#e6e6e6"

color0 = "#121212"
color1 = "#ffffff"
color2 = "#d8d8d8"
color3 = "#9c9c9c"
color4 = "#2e2e2e"
color5 = "#ffffff"
color6 = "#d8d8d8"
color7 = "#ffffff"
color8 = "#2e2e2e"
color9 = "#ffffff"
color10 = "#d8d8d8"
color11 = "#9c9c9c"
color12 = "#5a5a5a"
color13 = "#ffffff"
color14 = "#d8d8d8"
color15 = "#ffffff"
