set -g status-style "bg=default,fg=#d8d8d8"
set -g status-left "#[fg=#ffffff,bg=#2e2e2e,bold] #S #[fg=#d8d8d8,bg=default] "
set -g status-right "#[fg=#9c9c9c]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#d8d8d8]#h "
set -g window-status-format "#[fg=#9c9c9c] #I:#W "
set -g window-status-current-format "#[fg=#ffffff,bg=#2e2e2e,bold] #I:#W #[fg=#d8d8d8,bg=default]"
set -g pane-border-style "fg=#9c9c9c"
set -g pane-active-border-style "fg=#ffffff"
set -g message-style "bg=#121212,fg=#ffffff"
set -g message-command-style "bg=#121212,fg=#ffffff"
set -g mode-style "bg=#2e2e2e,fg=#ffffff"
set -g popup-style "bg=#121212,fg=#ffffff"
set -g popup-border-style "fg=#9c9c9c,bg=#121212"
set -g menu-style "bg=#121212,fg=#ffffff"
set -g menu-selected-style "bg=#2e2e2e,fg=#ffffff"
setw -g clock-mode-colour "#9c9c9c"
